schedules:
  - cron: "59 21 * * *"
    displayName: Destruição noturna do Ambiente
    branches:
      include:
        - development
      exclude:
        - main
    always: true

trigger: none
pr: none

pool:
  vmImage: ubuntu-latest

stages:
  - stage: Stage1
    displayName: Preparing for destruction
    jobs:
      - job: job1
        displayName: Gathering Destroy Template
    variables:
      - group: bbi-bold-profile-vars
  - template: stages/stage-destroy.yml
  - stage: Stage2
    displayName: Peering setup
    jobs:
      - job: RemoveVnetPeering
        displayName: Remove Vnet Peering
        pool:
          vmImage: ubuntu-latest
        steps:
          - task: AzureCLI@2
            inputs:
              azureSubscription: 'brbb-sp-terraform-azdevops'
              scriptType: 'bash'
              scriptLocation: 'inlineScript'
              inlineScript: 'az network vnet peering delete --name valhalla-to-boldprofile --vnet-name VNET_VALHALLA_CLOUD -g RGBBIVPNS2S'
