trigger:
  branches:
    exclude:
    - BI/*
    - TK/*
    - BG/*
    - FT/*

  paths:  
    exclude:
    - docs/*
    - documents/*
    - .devcontainer/*
    - terraform/bootstrap/*
    - terraform/templates/*
    - templates/*

pool:
  vmImage: ubuntu-latest

stages:

  - stage: CI
    displayName: Continuous Integration
    jobs: 
    - job: CIvalidation
    variables:
    - group: bbi-bold-profile-vars
  - template: stages/stages-ci.yml


  - stage: CD
    condition: succeeded() 
    displayName: Continuous Deployment
    jobs: 
    - job: "CD"
    variables:
    - group: bbi-bold-profile-vars
  - template: stages/stages-cd.yml