---
stages:        
- stage: CDStage
  variables:
    - group: bbi-bold-profile-vars
  displayName: Continuous Deployment
  jobs:
      
  - job: Apply
    displayName: Deployment Steps
    steps:
      - task: TerraformCLI@0
        displayName: Terraform init
        inputs:
          command: 'init'
          workingDirectory: '$(System.DefaultWorkingDirectory)'
          commandOptions: '-reconfigure'
          backendType: 'azurerm'
          backendServiceArm: ''
          backendAzureRmResourceGroupName: '$(TF-BACKEND-RESOURCE-GROUP)'
          backendAzureRmStorageAccountName: '$(TF-BACKEND-STORAGE-ACCOUNT)'
          backendAzureRmContainerName: '$(TF-BACKEND-CONTAINER)'
          backendAzureRmKey: '$(TF-BACKEND-KEY)'
          allowTelemetryCollection: true
      - task: TerraformCLI@0
        inputs:
          command: 'apply'
          workingDirectory: '$(System.DefaultWorkingDirectory)'
          environmentServiceName: ''
          commandOptions: '-var-file=../'
          allowTelemetryCollection: true
        displayName: 'Terraform Apply'