stages:
- stage: CIStage
  displayName: Continuous Integration
  variables:
    - group: kv-tf
  jobs:
  - job: InicializacaoTerraform
    displayName: Teste de Inicialização Terraform
    steps:
    - task: TerraformCLI@0

      inputs:
        command: 'init'
        workingDirectory: '$(System.DefaultWorkingDirectory)/stack/contoso'
        backendType: 'azurerm'
        backendServiceArm: 'ccs-dev-001'
        backendAzureRmResourceGroupName: '$(TF-BACKEND-RESOURCE-GROUP)'
        backendAzureRmStorageAccountName: '$(TF-BACKEND-STORAGE-ACCOUNT)'
        backendAzureRmContainerName: '$(TF-BACKEND-CONTAINER)'
        backendAzureRmKey: '$(TF-BACKEND-KEY)'
        allowTelemetryCollection: true
  - job: Validateterraform
    dependsOn: InicializacaoTerraform
    displayName: Validação do Código
    steps:
      - task: TerraformCLI@0
        inputs:
          command: 'validate'
          workingDirectory: '$(System.DefaultWorkingDirectory)/stack/contoso'
          allowTelemetryCollection: true

      - task: TerraformCLI@0
        inputs:
          command: 'fmt'
          workingDirectory: '$(System.DefaultWorkingDirectory)/stack/contoso'
          commandOptions: '-check -diff'
          allowTelemetryCollection: true
    
  - job: Terraformplan
    dependsOn: Validateterraform
    steps:
    - task: TerraformCLI@0

      inputs:
        command: 'init'
        workingDirectory: '$(System.DefaultWorkingDirectory)/stack/contoso'
        backendType: 'azurerm'
        backendServiceArm: 'ccs-dev-001'
        backendAzureRmResourceGroupName: '$(TF-BACKEND-RESOURCE-GROUP)'
        backendAzureRmStorageAccountName: '$(TF-BACKEND-STORAGE-ACCOUNT)'
        backendAzureRmContainerName: '$(TF-BACKEND-CONTAINER)'
        backendAzureRmKey: '$(TF-BACKEND-KEY)'
        allowTelemetryCollection: true
    - task: TerraformCLI@0
      inputs:
        command: 'plan'
        workingDirectory: '$(System.DefaultWorkingDirectory)/stack/contoso'
        environmentServiceName: 'ccs-dev-001'
        commandOptions: '-var-file=../../environments/dev/dev.tfvars'
        allowTelemetryCollection: true
        publishPlanResults: 'Terraform Plan'

- stage: Validation
  dependsOn: "CIStage"
  displayName: "Approval or Reject"
  variables:
    - group: kv-tf

  jobs: 
  - job: waitForValidation
    displayName: "Wait for manual approval"
    pool: "server"
    timeoutInMinutes: "4320" # job times out in 3 days
    steps:
    - task: ManualValidation@0
      timeoutInMinutes: 1440 # task times out in 1 day
      inputs:
        notifyUsers: |
          rafael.veloso@softwareone.com
        instructions: "There are resources being destroyed as part of this deployment, please review the output of Terraform plan before approving."
        onTimeout: "reject"
